dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

networks:
  sepolia:
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    host: "https://sepolia.infura.io/v3/580c5cb5596e40c5a03cf75178d09fb7"

